In [1]:
import numpy as np

Creating Arrays:

In [3]:
#create an arrays from a Python list
arr = np.array([1,2,3,4,5])
print(f"creates a {arr} array of zeros")

# Create an array filled with zeros

zeros_arr = np.zeros((3,4))
print(f"create a 3*4 array of zeros{zeros_arr}")

#Creates an array filled with ones
ones_arr=np.ones((2,3))
print(f"create a 2*3 array of ones {ones_arr}")

# create an array with a range of values
range_arr =np.arange(0,10,2)
print(f"ceates an array [0,2,3,4,6,8]={range_arr}")

#create an array with evenly spaced value
linspace_arr = np.linspace(0,1,5)
print(linspace_arr)



creates a [1 2 3 4 5] array of zeros
create a 3*4 array of zeros[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
create a 2*3 array of ones [[1. 1. 1.]
 [1. 1. 1.]]
ceates an array [0,2,3,4,6,8]=[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


Array Operations:

In [5]:
arr1 =np.array([1,2,3])
arr2 = np.array([1,2,4])
print(arr1,arr2)

# Arithmetic operations
addition = arr1 + arr2
print(f"addition {addition}")

minus = arr1 -arr2
print(f"minus= {minus}")

multiply = arr1 * arr2
print(f"multiply {multiply}")

divide = arr1 / arr2
print(f"divide {divide}")


[1 2 3] [1 2 4]
addition [2 4 7]
minus= [ 0  0 -1]
multiply [ 1  4 12]
divide [1.   1.   0.75]


In [8]:
# Element-wise operations

arr =np.array([1,8,3])
print(f"the array in which {arr}")
print(' ')
sqrt_arr = np.sqrt(arr)
print(f"squrt of arr = {arr}")

exp_arr = np.exp(arr)
print(f"expontion of array ={exp_arr}")

log_arr = np.log(arr)
print(f"log of the array = {log_arr}")



the array in which [1 8 3]
 
squrt of arr = [1 8 3]
expontion of array =[2.71828183e+00 2.98095799e+03 2.00855369e+01]
log of the array = [0.         2.07944154 1.09861229]


In [10]:
# Aggregation
print(arr)
arr_sum =np.sum(arr)
print(f"sum ={arr_sum}")
arr_mean = np.mean(arr)
print(f"arr_mean{arr_mean}")
arr_max = np.max(arr)
print(f'max{arr_max}')

arr_min = np.min(arr)
print(f"arr_min{arr_min}")

[1 8 3]
sum =12
arr_mean4.0
max8
arr_min1


Indexing and Slicing:

In [11]:
print(arr)
# Accessing elements
element =arr[0]
print(f"access the first element {element}")
last_element = arr[-1]
print(f'access the last element{last_element}')

#slicing 
subset =arr[2:5]
print(f"slice elements from index 2 to 4 (exclusive){subset}")

reverse_arr = arr[::-1]
print(f"reverse the array {reverse_arr}")


[1 8 3]
access the first element 1
access the last element3
slice elements from index 2 to 4 (exclusive)[3]
reverse the array [3 8 1]


Shape Manipulation:

In [15]:
print(arr)
# Reshaped and array
Reshaped_arr =arr.reshape((1,3))
print(f'reshape arr to a 1*3 array {Reshaped_arr}')

#Transose an array
Transose_arr = arr.T 
print(f"transepose ar{Transose_arr}")

# concatenate arrays
concatenated_arr = np.concatenate((arr,arr),axis=0)
print(f"cancanated array {concatenated_arr}")

[1 8 3]
reshape arr to a 1*3 array [[1 8 3]]
transepose ar[1 8 3]
cancanated array [1 8 3 1 8 3]


Linear Algebra Operations:

In [17]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8],
                 [9, 10],
                 [11, 12]])

# Matrix multiplication using np.dot()
mat_mult_dot = np.dot(arr1, arr2)
print(f"Matrix multiplication using np.dot():\n{mat_mult_dot}")
# Output:
# Matrix multiplication using np.dot():
# [[ 58  64]
#  [139 154]]

# Matrix multiplication using @ operator
mat_mult_simple = arr1 @ arr2
print(f"Matrix multiplication using @ operator:\n{mat_mult_simple}")
# Output:
# Matrix multiplication using @ operator:
# [[ 58  64]
#  [139 154]]




Matrix multiplication using np.dot():
[[ 58  64]
 [139 154]]
Matrix multiplication using @ operator:
[[ 58  64]
 [139 154]]


# Solving linear systems
solution = np.linalg.solve(coeff_matrix, const_vector)

# Computing eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [19]:
# Generate random integers
random_int = np.random.randint(low=0,high=10,size=(3,3))
print(f"generate a 3* 3 array of random integers{random_int}")

#Generate random floats
random_float = np.random.random(size=(2,2))
print(f"generate a 2*2 array of random floats between  0 and 1{random_float}")

#Set seed for reproducibility
s=np.random.seed(42)
print(s)

generate a 3* 3 array of random integers[[6 3 7]
 [4 6 9]
 [2 6 7]]
generate a 2*2 array of random floats between  0 and 1[[0.33370861 0.14286682]
 [0.65088847 0.05641158]]
None
